/*
 * Copyright (C) 2025 Texas Instruments Incorporated
 *
 * All rights reserved not granted herein.
 * Limited License.  
 *
 * Texas Instruments Incorporated grants a world-wide, royalty-free,
 * non-exclusive license under copyrights and patents it now or hereafter
 * owns or controls to make, have made, use, import, offer to sell and sell
 * ("Utilize") this software subject to the terms herein.  With respect to the
 * foregoing patent license, such license is granted  solely to the extent that
 * any such patent is necessary to Utilize the software alone.  The patent
 * license shall not apply to any combinations which include this software,
 * other than combinations with devices manufactured by or for TI
 * (TI Devices).  No hardware patent is licensed hereunder.
 *
 * Redistributions must preserve existing copyright notices and reproduce this
 * license (including the above copyright notice and the disclaimer and (if
 * applicable) source code license limitations below) in the documentation
 * and/or other materials provided with the distribution.
 *
 * Redistribution and use in binary form, without modification, are permitted
 * provided that the following conditions are met:
 *
 *	* No reverse engineering, decompilation, or disassembly of this software is
 *     permitted with respect to any software provided in binary form.
 *	* Any redistribution and use are licensed by TI for use only with
 *     TI Devices.
 *	* Nothing shall obligate TI to provide you with source code for the software
 *     licensed and provided to you in object code.
 *
 * If software source code is provided to you, modification and redistribution
 * of the source code are permitted provided that the following conditions are
 * met:
 *
 *   * any redistribution and use of the source code, including any resulting
 *     derivative works, are licensed by TI for use only with TI Devices.
 *   * any redistribution and use of any object code compiled from the source
 *     code and any resulting derivative works, are licensed by TI for use only
 *     with TI Devices.
 *
 * Neither the name of Texas Instruments Incorporated nor the names of its
 * suppliers may be used to endorse or promote products derived from this
 * software without specific prior written permission.
 *
 * DISCLAIMER.
 *
 * THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL TI AND TI'S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*!****************************************************************************
 *  @file       ec_curves.c
 *  @brief      Elliptic curve definitions
 *
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "ti/crypto/include/ec/ec_curves.h"

/* Definition of NIST P-256 EC Curve */

/**
 *  @brief      Buffer size for NIST P-256 curve parameters, in 32-bit words
 */
#define CRYPTO_EC_NISTP256_LEN (8U)

/**
 *  @brief      Prime modulus p for NIST P-256 curve
 *              p = 2^256 - 2^224 + 2^192 + 2^96 - 1
 */
const uint32_t Crypto_EC_NIST256_p[CRYPTO_EC_NISTP256_LEN+1U] = {
    CRYPTO_EC_NISTP256_LEN,
    4294967295UL, 4294967295UL, 4294967295UL, 0UL,
    0UL, 0UL, 1UL, 4294967295UL
};

/**
 *  @brief      Order r of the base point for NIST P-256 curve
 *              Size of the subgroup generated by the base point
 */
const uint32_t Crypto_EC_NIST256_r[CRYPTO_EC_NISTP256_LEN+1U] = {
    CRYPTO_EC_NISTP256_LEN,
    4234356049UL, 4089039554UL, 2803342980UL,
    3169254061UL, 4294967295UL, 4294967295UL, 0UL, 4294967295UL
};

/**
 *  @brief      Coefficient a for NIST P-256 curve
 *              Parameter in curve equation y^2 = x^3 + ax + b
 */
const uint32_t Crypto_EC_NIST256_a[CRYPTO_EC_NISTP256_LEN+1U] = {
    CRYPTO_EC_NISTP256_LEN,
    4294967292UL, 4294967295UL, 4294967295UL, 0UL,
    0UL, 0UL, 1UL, 4294967295UL
};

/**
 *  @brief      Coefficient b for NIST P-256 curve
 *              Parameter in curve equation y^2 = x^3 + ax + b
 */
const uint32_t Crypto_EC_NIST256_b[CRYPTO_EC_NISTP256_LEN+1U]  = {
    CRYPTO_EC_NISTP256_LEN,
    668098635UL, 1003371582UL, 3428036854UL,1696401072UL, 
    1989707452UL, 3018571093UL, 2855965671UL, 1522939352UL
};

/**
 *  @brief      x-coordinate of the base point G for NIST P-256 curve
 *              Base point is the generator of the main subgroup
 */
const uint32_t Crypto_EC_NIST256_Gx[CRYPTO_EC_NISTP256_LEN+1U] = {   
    CRYPTO_EC_NISTP256_LEN,
    3633889942UL, 4104206661UL, 770388896UL, 1996717441UL, 
    1671708914UL, 4173129445UL, 3777774151UL, 1796723186UL
};

/**
 *  @brief      y-coordinate of the base point G for NIST P-256 curve
 *              Base point is the generator of the main subgroup
 */
const uint32_t Crypto_EC_NIST256_Gy[CRYPTO_EC_NISTP256_LEN+1U] = {
    CRYPTO_EC_NISTP256_LEN,
    935285237UL, 3417718888UL, 1798397646UL, 734933847UL, 
    2081398294UL, 2397563722UL, 4263149467UL, 1340293858UL
};


/*
 *  @brief      Structure holding parameters for NIST P-256 (secp256r1) curve
 */
const crypto_ec_curve_t Crypto_EC_Curve_NIST256 = {
    .data_p = Crypto_EC_NIST256_p,
    .data_r = Crypto_EC_NIST256_r,
    .data_a = Crypto_EC_NIST256_a,
    .data_b = Crypto_EC_NIST256_b,
    .data_Gx = Crypto_EC_NIST256_Gx,
    .data_Gy = Crypto_EC_NIST256_Gy,
    .bufLen = CRYPTO_EC_NISTP256_LEN
};

/* Definition of NIST P-384 EC Curve */

/**
 *  @brief      Buffer size for NIST P-384 curve parameters, in 32-bit words
 */
#define CRYPTO_EC_NISTP384_LEN (12U)

/**
 *  @brief      Prime modulus p for NIST P-384 curve
 *              p = 2^384 - 2^128 - 2^96 + 2^32 - 1
 */
const uint32_t Crypto_EC_NIST384_p[CRYPTO_EC_NISTP384_LEN+1U] = {
    CRYPTO_EC_NISTP384_LEN,
    4294967295UL, 0UL, 0UL, 4294967295UL, 
    4294967294UL, 4294967295UL, 4294967295UL, 4294967295UL, 
    4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL
};

/**
 *  @brief      Order r of the base point for NIST P-384 curve
 *              Size of the subgroup generated by the base point
 */
const uint32_t Crypto_EC_NIST384_r[CRYPTO_EC_NISTP384_LEN+1U] = {
    CRYPTO_EC_NISTP384_LEN,
    3435473267UL, 3974895978UL, 1219536762UL, 1478102450UL, 
    4097256927UL, 3345173889UL, 4294967295UL, 4294967295UL,
    4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL
};

/**
 *  @brief      Coefficient a for NIST P-384 curve
 *              Parameter in curve equation y^2 = x^3 + ax + b
 */
const uint32_t Crypto_EC_NIST384_a[CRYPTO_EC_NISTP384_LEN+1U] = {
    CRYPTO_EC_NISTP384_LEN,
    4294967292UL, 0UL, 0UL, 4294967295UL, 
    4294967294UL, 4294967295UL, 4294967295UL, 4294967295UL, 
    4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL
};

/**
 *  @brief      Coefficient b for NIST P-384 curve
 *              Parameter in curve equation y^2 = x^3 + ax + b
 */
const uint32_t Crypto_EC_NIST384_b[CRYPTO_EC_NISTP384_LEN+1U] = {
    CRYPTO_EC_NISTP384_LEN,
    3555470063UL, 713410797UL, 2318324125UL, 3327539597UL, 
    1343457114UL, 51644559UL, 4269883666UL, 404593774UL,
    3824692505UL, 2559444331UL, 3795773412UL, 3006345127UL
};

/**
 *  @brief      x-coordinate of the base point G for NIST P-384 curve
 *              Base point is the generator of the main subgroup
 */
const uint32_t Crypto_EC_NIST384_Gx[CRYPTO_EC_NISTP384_LEN+1U] = {
    CRYPTO_EC_NISTP384_LEN,
    1920338615UL, 978607672UL, 3210029420UL, 1426256477UL, 
    2186553912UL, 1509376480UL, 2343017368UL, 1847409506UL,
    4079005044UL, 2394015518UL, 3196781879UL, 2861025826UL
};

/**
 *  @brief      y-coordinate of the base point G for NIST P-384 curve
 *              Base point is the generator of the main subgroup
 */
const uint32_t Crypto_EC_NIST384_Gy[CRYPTO_EC_NISTP384_LEN+1U] = {
    CRYPTO_EC_NISTP384_LEN,
    2431258207UL, 2051218812UL, 494829981UL, 174109134UL, 
    3052452032UL, 3923390739UL, 681186428UL, 4176747965UL,
    2459098153UL, 1570674879UL, 2519084143UL, 907533898UL
};

/*
 *  @brief      Structure holding parameters for NIST P-384 (secp384r1) curve
 */
const crypto_ec_curve_t Crypto_EC_Curve_NIST384 = {
    .data_p = Crypto_EC_NIST384_p,
    .data_r = Crypto_EC_NIST384_r,
    .data_a = Crypto_EC_NIST384_a,
    .data_b = Crypto_EC_NIST384_b,
    .data_Gx = Crypto_EC_NIST384_Gx,
    .data_Gy = Crypto_EC_NIST384_Gy,
    .bufLen = CRYPTO_EC_NISTP384_LEN
};

/* Definition of NIST P-521 EC Curve */

/**
 *  @brief      Buffer size for NIST P-521 curve parameters, in 32-bit words
 */
#define CRYPTO_EC_NISTP521_LEN (17U)

/**
 *  @brief      Prime modulus p for NIST P-521 curve
 *              p = 2^521 - 1
 */
const uint32_t Crypto_EC_NIST521_p[CRYPTO_EC_NISTP521_LEN+1U] = {
    CRYPTO_EC_NISTP521_LEN,
    4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL, 
    4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL, 
    4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL, 
    4294967295UL, 511UL
};

/**
 *  @brief      Order r of the base point for NIST P-521 curve
 *              Size of the subgroup generated by the base point
 */
const uint32_t Crypto_EC_NIST521_r[CRYPTO_EC_NISTP521_LEN+1U] = {
    CRYPTO_EC_NISTP521_LEN,
    2436391945UL, 3144660766UL, 2308720558UL, 1001769400UL, 4144604624UL, 
    2144076104UL, 3207566955UL, 1367771011UL, 4294967290UL, 4294967295UL, 
    4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL, 
    4294967295UL, 511UL
};

/**
 *  @brief      Coefficient a for NIST P-521 curve
 *              Parameter in curve equation y^2 = x^3 + ax + b
 */
const uint32_t Crypto_EC_NIST521_a[CRYPTO_EC_NISTP521_LEN+1U] = {
    CRYPTO_EC_NISTP521_LEN,
    4294967292UL, 4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL, 
    4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL, 
    4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL, 
    4294967295UL, 511UL
};

/**
 *  @brief      Coefficient b for NIST P-521 curve
 *              Parameter in curve equation y^2 = x^3 + ax + b
 */
const uint32_t Crypto_EC_NIST521_b[CRYPTO_EC_NISTP521_LEN+1U] = {
    CRYPTO_EC_NISTP521_LEN,
    1800421120UL, 4014284756UL, 1026307313UL,
    896786312UL, 1001504519UL, 374522045UL, 3967718267UL, 1444493649UL,
    2398161377UL, 3098839441UL, 2578650611UL, 2732225115UL, 3062186222UL,
    2459574688UL, 2384239135UL, 2503915873UL, 81UL
};

/**
 *  @brief      x-coordinate of the base point G for NIST P-521 curve
 *              Base point is the generator of the main subgroup
 */
const uint32_t Crypto_EC_NIST521_Gx[CRYPTO_EC_NISTP521_LEN+1U] = {
    CRYPTO_EC_NISTP521_LEN,
    3269836134UL, 4185816625UL, 2238333595UL, 860402625UL, 2734663902UL, 
    4263362855UL, 4024916264UL, 2706071159UL, 1800224186UL, 4163415904UL, 
    88061217UL, 2623832377UL, 597013570UL, 2654915430UL, 67430861UL,
    2240677559UL, 198UL
};

/**
 *  @brief      y-coordinate of the base point G for NIST P-521 curve
 *              Base point is the generator of the main subgroup
 */
const uint32_t Crypto_EC_NIST521_Gy[CRYPTO_EC_NISTP521_LEN+1U] = {
    CRYPTO_EC_NISTP521_LEN,
    2681300560UL, 2294191222UL, 2725429824UL, 893153414UL, 1068304225UL, 
    3310401793UL, 1593058880UL, 2548986521UL, 658400812UL, 397393175UL, 
    1469793384UL, 2566210633UL, 746396633UL, 1552572340UL, 2587607044UL, 
    959015544UL, 280UL
};

/*
 *  @brief      Structure holding parameters for NIST P-521 (secp521r1) curve
 */
const crypto_ec_curve_t Crypto_EC_Curve_NIST521 = {
    .data_p = Crypto_EC_NIST521_p,
    .data_r = Crypto_EC_NIST521_r,
    .data_a = Crypto_EC_NIST521_a,
    .data_b = Crypto_EC_NIST521_b,
    .data_Gx = Crypto_EC_NIST521_Gx,
    .data_Gy = Crypto_EC_NIST521_Gy,
    .bufLen = CRYPTO_EC_NISTP521_LEN
};
